### PR TITLE
Return all links as an array of objects 

### PR DESCRIPTION
**Pull request by adityacodes30**
W.r.t issue #13, this PR returns all the generated URLs in an array of JSON objects

```json
[  {"link" : "..." , "shortURL" : "..." }  ]
```

### CODE REVIEW

**Comment by adityacodes30** [comment]
@utkarsh-1905 i saw something has been updated while conflict resolution has this already been done ?

**Comment by MankiratSingh1315** [comment]
@adityacodes30 please remove the `main.exe` file

**Comment by MankiratSingh1315** [comment]
Change ni hua kuch
Rebase krow🙃

**Comment by adityacodes30** [comment]
repo deleted maybe

**Comment by adityacodes30** [comment]
done

**Comment by MankiratSingh1315** [comment]
Will miss you too buddy 😭
(but not the last project with MLSC people😉)

**Pull request merged**
