### PR TITLE
Introduce persistence in the Redis Cluster

### PR DESCRIPTION
**Pull request by MankiratSingh1315**
Issue solved #3

### CODE REVIEW

**Comment by utkarsh-1905** [comment]
@adityacodes30 can you test this out, by deploying the container and checking aof file?

**Comment by adityacodes30** [comment]
on it

**Comment by utkarsh-1905** [comment]
@adityacodes30 status?

**Review by adityacodes30 — APPROVED** [review]

**Comment by adityacodes30** [comment]
Lgtm, works as expected after stopping/removing and starting the containers

**Pull request merged**
